# Generated by Django 4.1.2 on 2023-08-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="name",),
    ]
