# Generated by Django 4.1.2 on 2023-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_user_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aboutus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField(max_length=400)),
                (
                    "image",
                    models.ImageField(
                        default="save_plant_logo.png", upload_to="organization_images"
                    ),
                ),
            ],
        ),
    ]
