# Generated by Django 4.1.2 on 2023-08-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_aboutus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=14)),
                ("facebook", models.CharField(max_length=200)),
                ("whatsapp", models.CharField(max_length=14)),
                ("twitter", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Contact us",},
        ),
        migrations.AlterModelOptions(
            name="aboutus", options={"verbose_name_plural": "About us"},
        ),
    ]
