# Generated by Django 4.1.2 on 2023-08-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0006_alter_contactus_facebook_alter_contactus_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="bkash_number",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donator_bkash_number", models.CharField(max_length=14, null=True)),
                ("money_transaction_id", models.CharField(max_length=200, null=True)),
                ("donation_amount", models.BigIntegerField()),
                (
                    "donator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="my_app.post",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
