# Generated by Django 4.1.2 on 2023-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_contactus_bkash_number_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
