# Generated by Django 4.1.2 on 2023-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0008_donation_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
