# Generated by Django 4.1.2 on 2023-08-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0011_rename_body_usernotification_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.post",
            ),
        ),
    ]
