# Generated by Django 4.1.2 on 2023-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_usernotification_created_at_usernotification_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
